export const staticHeroes = [
  {
    id: '001',
    name: 'athalia',
    faction: 'celestial',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '422_ath',
  },
  {
    id: '002',
    name: 'elijah & Lailah',
    faction: 'celestial',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '414_eli',
  },
  {
    id: '003',
    name: 'flora',
    faction: 'celestial',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '413_flo',
  },
  {
    id: '004',
    name: 'orthos',
    faction: 'celestial',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '401_ort',
  },
  {
    id: '005',
    name: 'talene',
    faction: 'celestial',
    base: 'agility',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '424_tal',
  },
  {
    id: '006',
    name: 'wu Kong',
    faction: 'celestial',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '400_wu ',
  },
  {
    id: '007',
    name: 'zaphreal',
    faction: 'celestial',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '413_zap',
  },
  {
    id: '008',
    name: 'alna',
    faction: 'celestial',
    base: 'agility',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '420_aln',
  },
  {
    id: '009',
    name: 'morael',
    faction: 'celestial',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '413_mor',
  },
  {
    id: '101',
    name: 'ezizh',
    faction: 'hypogean',
    base: 'strength',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '504_ezi',
  },
  {
    id: '102',
    name: 'mehira',
    faction: 'hypogean',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '513_meh',
  },
  {
    id: '103',
    name: 'zolrath',
    faction: 'hypogean',
    base: 'agility',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '520_zol',
  },
  {
    id: '104',
    name: 'khazard',
    faction: 'hypogean',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '513_kha',
  },
  {
    id: '105',
    name: 'mezoth',
    faction: 'hypogean',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '501_mez',
  },
  {
    id: '106',
    name: 'lucretia',
    faction: 'hypogean',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '522_luc',
  },
  {
    id: '107',
    name: 'mortas',
    faction: 'hypogean',
    base: 'agility',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '524_mor',
  },
  {
    id: '108',
    name: 'leofric',
    faction: 'hypogean',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '514_leo',
  },
  {
    id: '201',
    name: 'estrilda',
    faction: 'lightbearer',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '000_est',
  },
  {
    id: '202',
    name: 'belinda',
    faction: 'lightbearer',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '013_bel',
  },
  {
    id: '203',
    name: 'raine',
    faction: 'lightbearer',
    base: 'agility',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '024_rai',
  },
  {
    id: '204',
    name: 'rosaline',
    faction: 'lightbearer',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '014_ros',
  },
  {
    id: '205',
    name: 'lucius',
    faction: 'lightbearer',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '001_luc',
  },
  {
    id: '206',
    name: 'thane',
    faction: 'lightbearer',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '022_tha',
  },
  {
    id: '207',
    name: 'fawkes',
    faction: 'lightbearer',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '022_faw',
  },
  {
    id: '208',
    name: 'rowan',
    faction: 'lightbearer',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '014_row',
  },
  {
    id: '209',
    name: 'hendrik',
    faction: 'lightbearer',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '001_hen',
  },
  {
    id: '210',
    name: 'gwyneth',
    faction: 'lightbearer',
    base: 'strength',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '002_gwy',
  },
  {
    id: '211',
    name: 'rigby',
    faction: 'lightbearer',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '000_rig',
  },
  {
    id: '212',
    name: 'cecilia',
    faction: 'lightbearer',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '022_cec',
  },
  {
    id: '213',
    name: 'oscar',
    faction: 'lightbearer',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '022_osc',
  },
  {
    id: '214',
    name: 'eluard',
    faction: 'lightbearer',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '013_elu',
  },
  {
    id: '215',
    name: 'peggy',
    faction: 'lightbearer',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '014_peg',
  },
  {
    id: '216',
    name: 'walker',
    faction: 'lightbearer',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '000_wal',
  },
  {
    id: '301',
    name: 'brutus',
    faction: 'mauler',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '101_bru',
  },
  {
    id: '302',
    name: 'khaos',
    faction: 'mauler',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '100_kha',
  },
  {
    id: '303',
    name: 'vurk',
    faction: 'mauler',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '122_vur',
  },
  {
    id: '304',
    name: 'numisu',
    faction: 'mauler',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '114_num',
  },
  {
    id: '305',
    name: 'warek',
    faction: 'mauler',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '100_war',
  },
  {
    id: '306',
    name: 'skreg',
    faction: 'mauler',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '101_skr',
  },
  {
    id: '307',
    name: 'safiya',
    faction: 'mauler',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '113_saf',
  },
  {
    id: '308',
    name: 'satrana',
    faction: 'mauler',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '113_sat',
  },
  {
    id: '309',
    name: 'antandra',
    faction: 'mauler',
    base: 'agility',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '120_ant',
  },
  {
    id: '310',
    name: 'tidus',
    faction: 'mauler',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '122_tid',
  },
  {
    id: '311',
    name: 'skriath',
    faction: 'mauler',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '113_skr',
  },
  {
    id: '312',
    name: 'anoki',
    faction: 'mauler',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '100_ano',
  },
  {
    id: '313',
    name: 'drez',
    faction: 'mauler',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '122_dre',
  },
  {
    id: '314',
    name: 'kren',
    faction: 'mauler',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '122_kre',
  },
  {
    id: '401',
    name: 'nemora',
    faction: 'wilder',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '214_nem',
  },
  {
    id: '402',
    name: 'kaz',
    faction: 'wilder',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '222_kaz',
  },
  {
    id: '403',
    name: 'lyca',
    faction: 'wilder',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '222_lyc',
  },
  {
    id: '404',
    name: 'ulmus',
    faction: 'wilder',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '201_ulm',
  },
  {
    id: '405',
    name: 'gorvo',
    faction: 'wilder',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '201_gor',
  },
  {
    id: '406',
    name: 'eironn',
    faction: 'wilder',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '222_eir',
  },
  {
    id: '407',
    name: 'tasi',
    faction: 'wilder',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '214_tas',
  },
  {
    id: '408',
    name: 'seirus',
    faction: 'wilder',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '200_sei',
  },
  {
    id: '409',
    name: 'lorsan',
    faction: 'wilder',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '213_lor',
  },
  {
    id: '410',
    name: 'solise',
    faction: 'wilder',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '213_sol',
  },
  {
    id: '411',
    name: 'saurus',
    faction: 'wilder',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '200_sau',
  },
  {
    id: '412',
    name: 'pippa',
    faction: 'wilder',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '213_pip',
  },
  {
    id: '413',
    name: 'respen',
    faction: 'wilder',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '222_res',
  },
  {
    id: '414',
    name: 'raku',
    faction: 'wilder',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '222_rak',
  },
  {
    id: '501',
    name: 'grezhul',
    faction: 'graveborn',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '301_gre',
  },
  {
    id: '502',
    name: 'shemira',
    faction: 'graveborn',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '313_she',
  },
  {
    id: '503',
    name: 'oden',
    faction: 'graveborn',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '313_ode',
  },
  {
    id: '504',
    name: 'isabela',
    faction: 'graveborn',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '313_isa',
  },
  {
    id: '505',
    name: 'ferael',
    faction: 'graveborn',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '322_fer',
  },
  {
    id: '506',
    name: 'thoran',
    faction: 'graveborn',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '301_tho',
  },
  {
    id: '507',
    name: 'kelthur',
    faction: 'graveborn',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '322_kel',
  },
  {
    id: '508',
    name: 'nara',
    faction: 'graveborn',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '300_nar',
  },
  {
    id: '509',
    name: 'baden',
    faction: 'graveborn',
    base: 'agility',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '320_bad',
  },
  {
    id: '510',
    name: 'izold',
    faction: 'graveborn',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '300_izo',
  },
  {
    id: '511',
    name: 'torne',
    faction: 'graveborn',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '301_tor',
  },
  {
    id: '512',
    name: 'daimon',
    faction: 'graveborn',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '301_dai',
  },
  {
    id: '513',
    name: 'theowyn',
    faction: 'graveborn',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '322_the',
  },
  {
    id: '514',
    name: 'silas',
    faction: 'graveborn',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '314_sil',
  },
  {
    id: '515',
    name: 'desira',
    faction: 'graveborn',
    base: 'intelligence',
    class: 'support',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '314_des',
  },
  {
    id: '601',
    name: 'arthur',
    faction: 'dimensional',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '601_art',
  },
  {
    id: '602',
    name: 'nakoruru',
    faction: 'dimensional',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '622_nak',
  },
  {
    id: '603',
    name: 'ukyo',
    faction: 'dimensional',
    base: 'agility',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '620_uky',
  },
  {
    id: '604',
    name: 'ezio',
    faction: 'dimensional',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '622_ezi',
  },
  {
    id: '605',
    name: 'ainz Ooal Gown',
    faction: 'dimensional',
    base: 'intelligence',
    class: 'mage',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '613_ain',
  },
  {
    id: '606',
    name: 'albedo',
    faction: 'dimensional',
    base: 'strength',
    class: 'tank',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '601_alb',
  },
  {
    id: '607',
    name: 'joker',
    faction: 'dimensional',
    base: 'agility',
    class: 'ranger',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '622_jok',
  },
  {
    id: '608',
    name: 'queen',
    faction: 'dimensional',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '600_que',
  },
  {
    id: '609',
    name: 'prince Of Persia',
    faction: 'dimensional',
    base: 'strength',
    class: 'warrior',
    ascention: null,
    stars: null,
    si: null,
    furniture: null,
    bgImage: '622_pri',
  },
];
